config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]
  resources :locations

  get 'login' => 'sessions#new', as: :login  
  post 'login' => 'sessions#create'  
  post 'logout' => 'sessions#destroy', as: :logout
  

  root 'locations#index'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord

  belongs_to :user

  mount_uploaders :images, ImageUploader 
  serialize :images, JSON 

  geocoded_by :address # addressカラムを基準に緯度経度を算出する。
  after_validation :geocode # 住所変更時に緯度経度も変更する。
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :email, uniqueness: true

  has_many :locations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # before_action :require_login

  # private
  # # ログインをしていない場合の処理
  # def not_authenticated
  #   redirect_to login_path, alert: 'ログインしてください。'
  # end
  
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def index
    @locations = Location.all
    gon.locations = @locations
  end

  def show
    @location = Location.find(params[:id])
  end

  def new
    @location = Location.new
  end

  def create
    @location = current_user.locations.build(location_params)
    if @location.save
      redirect_to root_path
    else
      render :new
    end
  end


  
  private
  def location_params
    params.require(:location).permit( :address, :description, images: [])  # :latitude, :longitude のキーにも値を入れる必要がある
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  
  def index
    @locations = Location.all
    gon.locations = @locations
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = login(params[:email], params[:password])
    if @user.present?
      flash[:notice] = 'ログインしました'
      redirect_to root_path
    else
      flash[:danger] = 'ログインに失敗しました'
      render :new 
    end
  end

  def destroy
    logout
    flash[:notice] = 'ログアウトしました'
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | PortfolioSample
    = csrf_meta_tags
    = csp_meta_tag
    = include_gon
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  body
    = render '/shared/header'
    .container.mt-5
      = yield

app/views/locations/index.html.slim
- if flash
  - flash.each do |key, value|
    = content_tag :div, value, class: key
  

.row.helospace
  .helobaner.m-auto
    .image
      = image_tag "hawaiiGOPR0100.jpeg", class: "heloimage"
    .catchcopy
      | Good Discovery!! 


.row 
  h2.mx-auto 新着スポット
  .col-12.d-flex
    - @locations.each do |location|
      = link_to location_path(location) do
        .card.mx-3 id="map-#{location.id}"
          .card-header
            = image_tag location.images[0].url, size: "300x250"
          .card-body
            = location.address
          .card-footer
            .likes
              = icon 'fa', 'heart', + "x20"
            .badges.d-flex
              .badge.badge-info.m-1
                | #かわいい
              .badge.badge-info.m-1
                | #情熱的

          
br
br

div id = 'map_index' # idを付与, この部分にjsファイルで記述したGoogle Mapが埋め込まれる
- google_api = "https://maps.googleapis.com/maps/api/js?key=#{ ENV['GOOGLE_MAP_API'] }&callback=initMap".html_safe
script{ async src = google_api }

app/views/locations/new.html.slim
h1 ロケーション登録

.row 
  .col-4.mx-auto
    .card.form_location_new
      .card-body
        h2 新規登録
        = form_with model: @location, local: true do |f|
          .form-group
            = f.label :address, class: "bmd-label-floating"
            = f.text_field :address, class: "form-control"
          .form-group
            = f.label :images, class: "bmd-label-floating"
            = f.file_field :images, multiple: true, class: "form-control"
          .form-group
            = f.label :description, class: "bmd-label-floating"
            = f.text_area :description, class: "form-control"
          = f.submit "送信", class: "btn btn-success btn-raised"
            - binding.pry

app/views/locations/show.html.slim
.container.place_detail
  .row.place_imgs 
    .col-7.main_img
      = image_tag @location.images[0].url, class: "imgbox_main img-fluid"
    .col-4.sub_imgs
      .sub_img1
        = image_tag @location.images[0].url, class: "img img-fluid"
      - if @location.images[1]
        .sub_img2
          = image_tag @location.images[1].url, class: "img img-fluid"
      - else 
         .sub_img2
          = image_tag "http://design-ec.com/d/e_others_50/l_e_others_500.png", class: "img img-fluid"
      - if @location.images[2]
        .sub_img3
          = image_tag @location.images[2].url, class: "img img-fluid"
      - else 
         .sub_img3
          = image_tag "http://design-ec.com/d/e_others_50/l_e_others_500.png", class: "img img-fluid"  
  .row
    .col-12.place_description

app/views/posts/index.html.slim
- if flash
  - flash.each do |key, value|
    = content_tag :div, value, class: key
  

.row.helospace
  .helobaner.m-auto
    .image
      = image_tag "hawaiiGOPR0100.jpeg", class: "heloimage"
    .catchcopy
      | Good Discovery!! 


.row 
  .col-4.d-flex
    - @locations.each do |location|
      .location_image.m-2 id="map-#{location.id}" 
        = image_tag location.images[0].url, size: "200x200"
        = location.address
br
br

div id = 'map_index' # idを付与, この部分にjsファイルで記述したGoogle Mapが埋め込まれる
- google_api = "https://maps.googleapis.com/maps/api/js?key=#{ ENV['GOOGLE_MAP_API'] }&callback=initMap".html_safe
script{ async src = google_api }

app/views/posts/show.html.slim
.container.place_detail
  .row.place_imgs 
    .col-7.main_img
      = image_tag "https://picsum.photos/250/150", class: "imgbox_main img-fluid"
    .col-4.sub_imgs
      .sub_img1
        = image_tag "https://picsum.photos/250/150", class: "img img-fluid"
      .sub_img2
        = image_tag "https://picsum.photos/250/151", class: "img img-fluid" 
      .sub_img3 
        = image_tag "https://picsum.photos/250/152", class: "img img-fluid"  
  .row
    .col-12.place_description

app/views/shared/_header.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-white
  = link_to 'PortfolioSample', root_path, class: 'navbar-brand'
  button.navbar-toggler aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label=("Toggle navigation") data-target="#navbarTogglerDemo02" data-toggle="collapse" type="button"
    span.navbar-toggler-icon
  #navbarTogglerDemo02.collapse.navbar-collapse
    form.form-inline.my-2.my-lg-0.mr-auto
      input.form-control.mr-sm-2 placeholder="Search" type="search" /
      button.btn.btn-outline-success.my-2.my-sm-0 type="submit"  Search
    ul.navbar-nav.mt-2.mt-lg-0
      li.nav-item  
          = link_to '探してみる！！', '#', class: "nav-link"
      - if current_user
        li.nav-item 
          = link_to 'ロケーション登録', new_location_path, class: "nav-link"
        li.nav-item
          = link_to 'ログアウト', logout_path, method: :post, class: "nav-link"
      - else
        li.nav-item
          = link_to 'ログイン', login_path, class: "nav-link"

app/views/users/new.html.slim
.row 
  .col-4.mx-auto
    .card.form_users_new
      .card-body
        h2 新規登録
        = form_with model: @user, local: true do |f|
          .form-group
            = f.label :name, class: "bmd-label-floating"
            = f.text_field :name, class: "form-control"
          .form-group
            = f.label :email, class: "bmd-label-floating"
            = f.text_field :email, class: "form-control"
          .form-group
            = f.label :password, class: "bmd-label-floating"
            = f.password_field :password, class: "form-control"
          .form-group
            = f.label :password_confirmation, class: "bmd-label-floating"
            = f.password_field :password_confirmation, class: "form-control"
          = f.submit "送信", class: "btn btn-success btn-raised"
        